let maktabfaolatiObj = [
  {
    id: 1,
    title: "toshkent shaxar",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Toshkent shahar Mirzo Ulug'bek tumani, Oltintepa ko’chasi, 37A-uy",
    phone: "+998 97-966-77-37",
  },
  {
    id: 2,
    title: "toshkent Viloyati",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Toshkent viloyati Nurafshon shahri, Navro'z MFY",
    phone: "+998 94-622-42-02",
  },
  {
    id: 3,
    title: "sirdaryo",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Sirdaryo viloyati Guliston shahar, Bahor MFY",
    phone: "+998 94-667-35-11",
  },
  {
    id: 4,
    title: "jizzax",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Jizzax viloyati Sharof Rashidov tumani, Yangiobod mahallasi",
    phone: "+998 99-420-92-99",
  },
  {
    id: 5,
    title: "samarqand",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Samarqand viloyati Samarqand shahar,  Ro'daki ko'chasi",
    phone: "+998 97-502-20-10",
  },
  {
    id: 6,
    title: "qashqadaryo",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Qashqadaryo viloyati Qarshi shahri, Jayxun ko'chasi Мez-2",
    phone: "+998 97-502-20-10",
  },
  {
    id: 7,
    title: "surxondaryo",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Surxondaryo viloyati Termez tumani, Yangiobod mahallasi",
    phone: "+998 91-971-71-13",
  },
  {
    id: 8,
    title: "namangan",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Namangan viloyati Namangan shahar, Davlatobod tumani, Mustqaillik ko'chasi",
    phone: "+998 97-762-72-68",
  },
  {
    id: 9,
    title: "farg’ona",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Farg'ona viloyati Fargona tumani, Ilgor MFY, Obodturmush ",
    phone: "+998 95-016-04-86",
  },
  {
    id: 10,
    title: "andijon",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Andijon viloyati Andijon tumani, O'rikzor MFY, Sattazor ko'chasi",
    phone: "+998 97-964-66-26",
  },
  {
    id: 11,
    title: "navoiy",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: "Navoiy viloyati, Navoiy shahar, Sputnik Qo'rg'oni ",
    phone: "+998 91-335-57-99",
  },
  {
    id: 12,
    title: "buxoro",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: `Buxoro viloyati, Buxoro tumani, "Sheyxoncha" MFY "Dechabegi" qishlog'i`,
    phone: "+998 93-657-03-33",
  },
  {
    id: 13,
    title: "xorazm",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: `Xorazm viloyati Urganch tumani, Killovud MFY`,
    phone: "+998 97-737-03-24",
  },
  {
    id: 14,
    title: "qoraqalpog’iston respublikasi",
    img: "../images/location.svg",
    img2: "../images/phone.svg",
    location: `Qoraqalpog'iston Respublikasi Nukus shahri, Taxiatosh guzari`,
    phone: "+998 97-474-85-58",
  },
]